const STORAGE_KEY='familia-presupuesto-v2';
const money=n=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(Number(n)||0);
const shortMoney=n=>{const v=Number(n)||0;return Math.abs(v)>=1e6?`${(v/1e6).toFixed(v%1e6===0?0:1)} M`:money(v)};
const shortMonth=m=>new Intl.DateTimeFormat('es-CO',{month:'short'}).format(new Date(m+'-01T12:00:00')).replace('.','');
const addMonths=(m,n)=>{const d=new Date(m+'-01T12:00:00');d.setMonth(d.getMonth()+n);return d.toISOString().slice(0,7)};
const currentMonth=()=>new Date().toISOString().slice(0,7);
function readData(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}catch{return{}}}
function loanEnd(x,startMonth){if(x.loanEndMonth)return x.loanEndMonth;if(x.totalInstallments){const start=x.loanStartMonth||startMonth,cur=Math.max(1,+x.currentInstallment||1),total=Math.max(cur,+x.totalInstallments||cur);return addMonths(start,total-cur)}return''}
function fixedIsActive(x,m,startMonth){if((+x.amount||0)<=0)return false;if((x.kind||'regular')!=='loan')return true;const start=x.loanStartMonth||startMonth,end=loanEnd(x,startMonth);return m>=start&&(!end||m<=end)}
function monthsForYear(year,startMonth){return Array.from({length:12},(_,i)=>`${year}-${String(i+1).padStart(2,'0')}`).filter(m=>m>=startMonth)}
function rowsFor(year){const data=readData(),startMonth=data.startMonth||'2026-08',now=currentMonth(),income=(data.income||[]).reduce((a,x)=>a+(+x.amount||0),0);return monthsForYear(year,startMonth).map(k=>{const isActual=k<=now;const fixed=(data.fixed||[]).filter(x=>fixedIsActive(x,k,startMonth));const paidMap=data.fixedPayments?.[k]||{};const paidFixed=fixed.reduce((a,x)=>a+(paidMap[x.id]?(+x.amount||0):0),0);const variable=(data.expenses||[]).filter(e=>(e.date||'').slice(0,7)===k).reduce((a,e)=>a+(+e.amount||0),0);const ingreso=isActual?income:0;const gasto=isActual?paidFixed+variable:0;return{k,ingreso,gasto,ahorro:ingreso-gasto,isActual}})}
function sum(rows,key){return rows.reduce((a,r)=>a+(r.isActual?r[key]:0),0)}
function linePath(points){return points.map((p,i)=>`${i?'L':'M'} ${p.x.toFixed(2)} ${p.y.toFixed(2)}`).join(' ')}
function ensureBlock(main,cls,after){let el=main.querySelector(`:scope > .${cls}`);if(!el){el=document.createElement('section');el.className=`card ${cls}`;after?.insertAdjacentElement('afterend',el)}return el}
function detailHtml(rows){const max=Math.max(...rows.flatMap(r=>[r.ingreso,r.gasto,Math.abs(r.ahorro)]),1);return `<div class="annualDetailHead"><small>DETALLE POR MES</small><h2>Ingresos, gastos y ahorro</h2></div><div class="annualDetailList">${rows.map(r=>`<div class="annualActualMonth ${!r.isActual?'futureMonth':''}"><div class="actualMonthHead"><b>${shortMonth(r.k)}</b><span>${r.isActual?`${money(r.ahorro)} Ahorro`:'Sin Movimientos Aún'}</span></div><div class="actualBarRow"><span>Ingreso</span><i><em class="incomeFill" style="width:${r.isActual?r.ingreso/max*100:0}%"></em></i><b>${r.isActual?money(r.ingreso):'—'}</b></div><div class="actualBarRow"><span>Gasto</span><i><em class="expenseFill" style="width:${r.isActual?r.gasto/max*100:0}%"></em></i><b>${r.isActual?money(r.gasto):'—'}</b></div><div class="actualBarRow"><span>Ahorro</span><i><em class="${r.ahorro<0?'savingFill negativeFill':'savingFill'}" style="width:${r.isActual?Math.abs(r.ahorro)/max*100:0}%"></em></i><b class="${r.ahorro<0?'badText':''}">${r.isActual?money(r.ahorro):'—'}</b></div></div>`).join('')}</div>`}
function render(){const card=document.querySelector('.annualCard.annualPro');if(!card){document.querySelectorAll('.annualProgressBlock,.annualDetailBlock').forEach(el=>el.remove());return}const main=card.parentElement;const select=card.querySelector('.annualTop select');const year=select?.value||String(new Date().getFullYear());const rows=rowsFor(year);const actualRows=rows.filter(r=>r.isActual),incomeTotal=sum(rows,'ingreso'),expenseTotal=sum(rows,'gasto'),savingTotal=sum(rows,'ahorro');let summary=card.querySelector('.cashyAnnualSummary');if(!summary){summary=document.createElement('div');summary.className='cashyAnnualSummary';card.querySelector('.annualTop')?.insertAdjacentElement('afterend',summary)}summary.innerHTML=`<div class="actualMetrics"><div><small>INGRESOS</small><strong>${money(incomeTotal)}</strong></div><div><small>GASTOS</small><strong>${money(expenseTotal)}</strong></div><div class="${savingTotal<0?'negative':''}"><small>AHORRO</small><strong>${money(savingTotal)}</strong></div></div>`;const progress=ensureBlock(main,'annualProgressBlock',card);const detail=ensureBlock(main,'annualDetailBlock',progress);const W=760,H=300,pad={l:46,r:18,t:24,b:42};const values=actualRows.flatMap(r=>[r.ingreso,r.gasto,r.ahorro]);const max=Math.max(...values.map(v=>Math.max(0,v)),1),min=Math.min(...values,0);const range=Math.max(1,max-min);const x=i=>pad.l+(actualRows.length<=1?(W-pad.l-pad.r)/2:i*(W-pad.l-pad.r)/(actualRows.length-1));const y=v=>pad.t+(max-v)*(H-pad.t-pad.b)/range;const series=[['ingreso','incomeLine'],['gasto','expenseLine'],['ahorro','savingLine']];const paths=series.map(([key,cls])=>{const pts=actualRows.map((r,i)=>({x:x(i),y:y(r[key]),v:r[key],m:r.k}));return `<path class="${cls}" d="${linePath(pts)}"/>${pts.map(p=>`<circle class="${cls} point" cx="${p.x}" cy="${p.y}" r="4"><title>${shortMonth(p.m)} · ${money(p.v)}</title></circle>`).join('')}`}).join('');const grid=[0,.25,.5,.75,1].map(t=>{const val=min+(max-min)*t,yy=y(val);return `<line x1="${pad.l}" x2="${W-pad.r}" y1="${yy}" y2="${yy}"/><text x="${pad.l-8}" y="${yy+4}" text-anchor="end">${shortMoney(val)}</text>`}).join('');const labels=actualRows.map((r,i)=>`<text x="${x(i)}" y="${H-14}" text-anchor="middle">${shortMonth(r.k)}</text>`).join('');progress.innerHTML=`<div class="actualChartTitle"><div><small>PROGRESO DEL AÑO</small><b>Ingreso vs gasto vs ahorro</b></div><span>Solo meses con movimientos</span></div>${actualRows.length?`<div class="lineChartWrap"><svg class="actualLineChart" viewBox="0 0 ${W} ${H}" role="img" aria-label="Progreso anual de ingresos, gastos y ahorro"><g class="grid">${grid}</g><g class="monthLabels">${labels}</g><g class="series">${paths}</g></svg></div>`:`<div class="emptyAnnual">Aún no hay movimientos para graficar.</div>`}<div class="actualLegend"><span><i class="incomeActual"></i>Ingresos</span><span><i class="expenseActual"></i>Gastos</span><span><i class="savingActual"></i>Ahorro</span></div>`;detail.innerHTML=detailHtml(rows)}
let queued=false;function schedule(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;render()})}const observer=new MutationObserver(schedule);observer.observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['class','value']});document.addEventListener('change',e=>{if(e.target.closest?.('.annualTop'))setTimeout(render,0)});window.addEventListener('storage',schedule);setInterval(render,1200);schedule();