const ORDER_KEY='cashy-tab-block-order-v1';
const TAB_LABELS={Inicio:'inicio',Gastos:'gastos',Mes:'config',Plan:'plan',Año:'resumen'};
function readOrders(){try{return JSON.parse(localStorage.getItem(ORDER_KEY)||'{}')}catch{return{}}}
function writeOrders(v){localStorage.setItem(ORDER_KEY,JSON.stringify(v))}
function currentTab(){const active=document.querySelector('nav button.active span');return TAB_LABELS[active?.textContent?.trim()]||'unknown'}
function signature(el,index){const cls=[...el.classList].filter(c=>!['reorderableBlock','reorderActive'].includes(c)).join('.');const title=el.querySelector('h1,h2,strong,small')?.textContent?.trim().replace(/\s+/g,' ').slice(0,50)||'';return `${cls}|${title||index}`}
function ensureControls(el){if(el.querySelector(':scope > .blockReorderControls'))return;const box=document.createElement('div');box.className='blockReorderControls';box.innerHTML='<span>Orden</span><button type="button" aria-label="Mover arriba">↑</button><button type="button" aria-label="Mover abajo">↓</button>';const [up,down]=box.querySelectorAll('button');up.addEventListener('click',e=>{e.stopPropagation();move(el,-1)});down.addEventListener('click',e=>{e.stopPropagation();move(el,1)});el.prepend(box)}
function saveCurrent(){const main=document.querySelector('.app main');if(!main)return;const tab=currentTab();const blocks=[...main.children].filter(x=>x.matches('section'));const orders=readOrders();orders[tab]=blocks.map((el,i)=>el.dataset.orderKey||signature(el,i));writeOrders(orders)}
function move(el,dir){const main=el.parentElement;if(!main)return;const blocks=[...main.children].filter(x=>x.matches('section'));const i=blocks.indexOf(el),j=i+dir;if(j<0||j>=blocks.length)return;if(dir<0)main.insertBefore(el,blocks[j]);else main.insertBefore(blocks[j],el);saveCurrent();decorate()}
function applySaved(main,tab){const blocks=[...main.children].filter(x=>x.matches('section'));blocks.forEach((el,i)=>{if(!el.dataset.orderKey)el.dataset.orderKey=signature(el,i)});const saved=readOrders()[tab];if(!saved?.length)return;const rank=new Map(saved.map((k,i)=>[k,i]));const sorted=[...blocks].sort((a,b)=>(rank.has(a.dataset.orderKey)?rank.get(a.dataset.orderKey):999)-(rank.has(b.dataset.orderKey)?rank.get(b.dataset.orderKey):999));if(sorted.some((el,i)=>el!==blocks[i]))sorted.forEach(el=>main.appendChild(el))}
let busy=false;function decorate(){if(busy)return;busy=true;requestAnimationFrame(()=>{const main=document.querySelector('.app main');if(!main){busy=false;return}const tab=currentTab();applySaved(main,tab);const blocks=[...main.children].filter(x=>x.matches('section'));blocks.forEach((el,i)=>{el.classList.add('reorderableBlock');if(!el.dataset.orderKey)el.dataset.orderKey=signature(el,i);ensureControls(el);const btns=el.querySelectorAll(':scope > .blockReorderControls button');if(btns.length===2){btns[0].disabled=i===0;btns[1].disabled=i===blocks.length-1}});busy=false})}
const observer=new MutationObserver(decorate);observer.observe(document.documentElement,{childList:true,subtree:true});document.addEventListener('click',e=>{if(e.target.closest('nav button'))setTimeout(decorate,0)});decorate();